### ISSUE TITLE
提问: 依赖问题

### ISSUE THREAD

**Issue by helloLiRong** [edwingeng/hotswap#4]
你好，我最近在看go-plugin的相关文档，发现它有需要限制。对我们来说最主要的是版本冲突的问题。
你的项目应该是解决go-plugin版本冲突的问题。
请问你是如何解决这个问题的？例如main程序和plugin程序依赖的第三方包版本不一致。

**Comment by edwingeng** [comment]
建议把 plugin 和宿主程序放在一个 repo 里，依赖就一样了，否则麻烦多多。『放在一起』这件事有个变种：分两个 repo，一个存宿主程序，一个存 plugin。宿主程序的 main package 要特别薄，只含 main.go，只有几行代码，不触及任何业务功能，然后把这个 main.go 复制到 plugin 的 repo，令其引用宿主程序的 repo，最后，编译宿主程序的时候，在 plugin 的 repo 编译。
