### ISSUE TITLE
大佬介绍一下原理，以及cgo需要主程序开启吗，性能怎么优化

### ISSUE THREAD

**Issue by introspection3** [edwingeng/hotswap#5]
谢谢老板

**Comment by edwingeng** [comment]
谈不上什么原理，只是解决了 plugin 编译、加载过程中遇到的几个问题。

宿主程序必须开 cgo，这是 golang plugin 的硬要求。

正常情况下，这套机制不会制造性能瓶颈，几乎就是纯原生运行效率，所以性能方面不需要特别注意什么。
